[[constraint]]
  branch = "master"
  name = "github.com/ditashi/jsbeautifier-go"

[[constraint]]
  name = "github.com/dsnet/compress"
  version = "0.0.1"

[[constraint]]
  name = "github.com/evilsocket/islazy"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gocolly/colly"
  #version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/logrusorgru/aurora"

[[constraint]]
  branch = "master"
  name = "github.com/lucasjones/reggen"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  branch = "master"
  #version = "0.3.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  #branch = "master"
  name = "gopkg.in/resty.v1"
  version = "1.12.0"

[[constraint]]
  branch = "master"
  name = "mvdan.cc/xurls"
  # version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
